# Generated by Django 4.1.1 on 2022-09-28 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_favori'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favori',
            name='geyim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clothes_add', to='shop.clothes'),
        ),
    ]
