# Generated by Django 4.1.1 on 2022-09-30 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_checkout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='date',
        ),
    ]
