# Generated by Django 4.1.1 on 2022-10-03 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_remove_checkout_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Checkout',
        ),
    ]
