# Generated by Django 4.1.1 on 2022-10-05 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_delete_checkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='draft',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
