# Generated by Django 4.1.1 on 2022-11-11 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_addimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothes',
            name='image',
        ),
    ]
