# Generated by Django 4.1.1 on 2022-09-29 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
