# Generated by Django 4.1.1 on 2022-10-10 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_delete_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='phone',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
